### ISSUE TITLE
path to socket too long leads to cryptic failure

### ISSUE THREAD

**Issue by jjelinek** [jclulow/vmware-sercons#1]
In make_conn, if the path to the socket is greater than ua.sun_path (108 bytes), the function returns with errno == 0 and the program exits with this message:

```
errno 0
opening serial socket: Undefined error: 0
```

**Comment by jclulow** [comment]
This should be fixed in 43e3b31.  I tested it by creating a really long symlink (~160 characters total path length) and seeing that `sercons` connected successfully anyway.
