### ISSUE TITLE
Build fails on Mac OS Mojave

### ISSUE THREAD

**Issue by rejohnst** [jclulow/vmware-sercons#5]
The build fails on Mac OS Mojave (see error msgs below).  Looks like it's because the Makefile specifies the "-m32" CFLAG to build a 32-bit i386 version, but I believe the SDK shipped in Mojave no longer includes 32-bit versions of the libraries.  In fact Mojave is supposed to be the last version that will even support running 32-bit apps.  Remove this line from the Makefile allowed the build to succeed:

```diff
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,6 @@ OS := $(shell uname)
 
 CFLAGS = -Wall -Wextra -Werror
 ifeq ($(OS),Darwin)
-CFLAGS += -m32
 CFLAGS += -mmacosx-version-min=10.6
 endif
 ifeq ($(OS),SunOS)
```

<pre>
$ make
gcc -Wall -Wextra -Werror -m32 -mmacosx-version-min=10.6 -o sercons sercons.c
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "___error", referenced from:
      _main in sercons-aecbd4.o
      _make_conn in sercons-aecbd4.o
  "___stack_chk_fail", referenced from:
      _raw_mode in sercons-aecbd4.o
  "___stack_chk_guard", referenced from:
      _raw_mode in sercons-aecbd4.o
  "___stderrp", referenced from:
      _main in sercons-aecbd4.o
  "___strcpy_chk", referenced from:
      _make_conn in sercons-aecbd4.o
  "_abort", referenced from:
      _main in sercons-aecbd4.o
      _wait_for_end in sercons-aecbd4.o
      _post_end in sercons-aecbd4.o
  "_calloc", referenced from:
      _make_conn in sercons-aecbd4.o
  "_close$UNIX2003", referenced from:
      _make_conn in sercons-aecbd4.o
  "_connect$UNIX2003", referenced from:
      _make_conn in sercons-aecbd4.o
  "_exit", referenced from:
      start in crt1.10.6.o
      _main in sercons-aecbd4.o
      _open_logfile in sercons-aecbd4.o
  "_fflush", referenced from:
      _main in sercons-aecbd4.o
  "_fprintf", referenced from:
      _main in sercons-aecbd4.o
  "_free", referenced from:
      _make_conn in sercons-aecbd4.o
  "_fsync$UNIX2003", referenced from:
      _open_logfile in sercons-aecbd4.o
      _copy_thread in sercons-aecbd4.o
  "_getopt$UNIX2003", referenced from:
      _main in sercons-aecbd4.o
  "_memcpy", referenced from:
      _raw_mode in sercons-aecbd4.o
  "_open$UNIX2003", referenced from:
      _main in sercons-aecbd4.o
      _open_logfile in sercons-aecbd4.o
  "_optarg", referenced from:
      _main in sercons-aecbd4.o
  "_optind", referenced from:
      _main in sercons-aecbd4.o
  "_optopt", referenced from:
      _main in sercons-aecbd4.o
  "_perror", referenced from:
      _main in sercons-aecbd4.o
      _open_logfile in sercons-aecbd4.o
  "_pthread_cond_broadcast", referenced from:
      _post_end in sercons-aecbd4.o
  "_pthread_cond_wait$UNIX2003", referenced from:
      _wait_for_end in sercons-aecbd4.o
  "_pthread_create", referenced from:
      _main in sercons-aecbd4.o
  "_pthread_mutex_lock", referenced from:
      _wait_for_end in sercons-aecbd4.o
      _post_end in sercons-aecbd4.o
  "_pthread_mutex_unlock", referenced from:
      _wait_for_end in sercons-aecbd4.o
      _post_end in sercons-aecbd4.o
  "_read$UNIX2003", referenced from:
      _copy_thread in sercons-aecbd4.o
  "_sleep$UNIX2003", referenced from:
      _main in sercons-aecbd4.o
  "_socket", referenced from:
      _make_conn in sercons-aecbd4.o
  "_strlen", referenced from:
      _open_logfile in sercons-aecbd4.o
      _make_conn in sercons-aecbd4.o
  "_tcgetattr", referenced from:
      _raw_mode in sercons-aecbd4.o
  "_tcsetattr", referenced from:
      _raw_mode in sercons-aecbd4.o
      _reset_mode in sercons-aecbd4.o
  "_write$UNIX2003", referenced from:
      _main in sercons-aecbd4.o
      _open_logfile in sercons-aecbd4.o
      _copy_thread in sercons-aecbd4.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sercons] Error 1
</pre>

**Comment by jclulow** [comment]
We should probably determine a new value for `macosx-version-min` at the same time.

**Comment by bahamat** [comment]
64-bit was supported on 10.4.7 and later. 10.7.0 and later will only run on 64-bit processors.

**Comment by jclulow** [comment]
This should be fixed by @mgerdts now I believe.
